export const getEnglishPokemonName = (chineseName: string): string => {
  const map: Record<string, string> = {
    '皮卡丘': 'Pikachu',
    '噴火龍': 'Charizard',
    '妙蛙種子': 'Bulbasaur',
    '水箭龜': 'Blastoise',
    '伊布': 'Eevee',
    '卡比獸': 'Snorlax',
    '耿鬼': 'Gengar',
    '路卡利歐': 'Lucario',
    '烈空坐': 'Rayquaza',
    '沙奈朵': 'Gardevoir',
    '洛奇亞': 'Lugia',
    '鳳王': 'Ho-Oh',
    '超夢': 'Mewtwo',
    '夢幻': 'Mew',
    '百變怪': 'Ditto',
    '甲賀忍蛙': 'Greninja',
    '阿爾宙斯': 'Arceus',
    '固拉多': 'Groudon',
    '蓋歐卡': 'Kyogre',
    '蒼響': 'Zacian',
    '藏瑪然特': 'Zamazenta',
    '水君': 'Suicune',
    '拉帝亞斯': 'Latias',
    '拉帝歐斯': 'Latios',
  }
  return map[chineseName.trim()] || chineseName.trim()
}

export const getJapanesePokemonName = (chineseName: string): string => {
  const map: Record<string, string> = {
    '皮卡丘': 'ピカチュウ',
    '噴火龍': 'リザードン',
    '妙蛙種子': 'フシギダネ',
    '水箭龜': 'カメックス',
    '耿鬼': 'ゲンガー',
    '卡比獸': 'カビゴン',
    '急凍鳥': 'フリーザー',
    '閃電鳥': 'サンダー',
    '火焰鳥': 'ファイヤー',
    '迷你龍': 'ミニリュウ',
    '快龍': 'カイリュー',
    '超夢': 'ミュウツー',
    '夢幻': 'ミュウ',
    '洛奇亞': 'ルギア',
    '鳳王': 'ホウオウ',
    '炎帝': 'エンテイ',
    '水君': 'スイクン',
    '雷公': 'ライコウ',
    '拉帝亞斯': 'ラティアス',
    '拉帝歐斯': 'ラティオス',
    '固拉多': 'グラードン',
    '蓋歐卡': 'カイオーガ',
    '烈空坐': 'レックウザ',
    '路卡利歐': 'ルカリオ',
    '沙奈朵': 'サーナイト',
    '阿爾宙斯': 'アルセウス',
    '甲賀忍蛙': 'ゲッコウガ',
    '伊布': 'イーブイ',
    '水伊布': 'シャワーズ',
    '雷伊布': 'サンダース',
    '火伊布': 'ブースター',
    '太陽伊布': 'エーフィ',
    '月亮伊布': 'ブラッキー',
    '葉伊布': 'リーフィア',
    '冰伊布': 'グレイシア',
    '仙子伊布': 'ニンフィア',
    '百變怪': 'メタモン',
    '蒼響': 'ザシアン',
    '藏瑪然特': 'ザマゼンタ',
    '武道熊師': 'ウーラオス',
  }
  return map[chineseName.trim()] || chineseName.trim()
}
